### ISSUE TITLE
Error when building with --watch and --aot flags

### ISSUE THREAD

**Issue by icecoldfire** [FortAwesome/angular-fontawesome#78]
When the cli pick-ups and file that was changed I get the following error:

ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '@angular/router.ngfactory' in '\ClientApp\src\app'
ERROR in ./src/app/core/buttons/btn-save.component.ngfactory.js
Module not found: Error: Can't resolve '@fortawesome/angular-fontawesome.ngfactory' in '\ClientApp\src\app\core\buttons'
ERROR in ./src/app/home/compare/compare.component.ngfactory.js
Module not found: Error: Can't resolve '@fortawesome/angular-fontawesome.ngfactory' in '\ClientApp\src\app\home\compare'
ERROR in ./src/app/home/director/director.component.ngfactory.js
Module not found: Error: Can't resolve '@fortawesome/angular-fontawesome.ngfactory' in '\ClientApp\src\app\home\director'
ERROR in ./src/app/home/employee/employee.component.ngfactory.js
Module not found: Error: Can't resolve '@fortawesome/angular-fontawesome.ngfactory' in '\ClientApp\src\app\home\employee'
ERROR in ./src/app/home/sole-trader/sole-trader.component.ngfactory.js
Module not found: Error: Can't resolve '@fortawesome/angular-fontawesome.ngfactory' in '\ClientApp\src\app\home\sole-trader'

I'm using the following packages:

  "dependencies": {
    "@angular/animations": "6.1.2",
    "@angular/common": "6.1.2",
    "@angular/compiler": "6.1.2",
    "@angular/core": "6.1.2",
    "@angular/forms": "6.1.2",
    "@angular/http": "6.1.2",
    "@angular/platform-browser": "6.1.2",
    "@angular/platform-browser-dynamic": "6.1.2",
    "@angular/router": "6.1.2",
    "bootstrap": "4.1.3",
    "bootstrap-datepicker": "1.8.0",
    "core-js": "2.5.7",
    "jquery": "3.3.1",
    "moment": "2.22.2",
    "rxjs": "6.2.2",
    "zone.js": "0.8.26",
    "@fortawesome/angular-fontawesome": "0.1.1",
    "@fortawesome/fontawesome-svg-core": "1.2.2",
    "@fortawesome/free-regular-svg-icons": "5.2.0",
    "@fortawesome/free-solid-svg-icons": "5.2.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "6.1.2",
    "@angular-devkit/build-angular": "0.7.2",
    "typescript": "2.7.2",
    "@angular/cli": "6.1.2",
    "@angular/language-service": "6.1.2",
    "@types/node": "8.9.4",
    "ts-node": "7.0.0",
    "tslint": "5.11.0"
  }

**Comment by icecoldfire** [comment]
Angular version 6.1.2 gives the error when using version 6.0.9 everything works.

**Comment by Neofish22** [comment]
I am having the same issue. I've spent some time trying to find a cause but haven't had any luck. Notably, the build succeeds the first time, but fails on any successive build from --watch. I have enabled options for additional type checking, etc. I'll provide details/logs/confs and I'll try to make a reproduced repo, tomorrow.

**Comment by Neofish22** [comment]
I started working through creating a repo to reproduce the bug. Initially I did get errors as in your OP. I added another, different module to check it wasn't an issue with Angular rather than FontAwesome. I continued to get the same style of errors. However, after switching between enabling FontAwesome and the other module, the errors stopped entirely for FontAwesome (but not for the other). I am unsure what could cause that behaviour. Despite this I have uploaded the repos anyway:
https://github.com/Neofish22/angular-bug-reproduction-01
The README covers everything I did and refers back here.

Additionally, it seems Angular released 6.1.3 since our posts here. I updated to this (because `ng new` used 6.0.8) before beginning. However, I updated in the same way on my proper project and I still get the errors. I ought to fiddle around more to try and solve the issue, but I'm inclined to downgrade to 6.0.9 per your advice and get on with the project.

**Comment by devoto13** [comment]
@Neofish22 I tried to run your reproduction and was unable to reproduce compilation error. 

Here is what I did:
1. Cloned the repro.
2. `ng serve --watch`
3. Edited templated of the `AppComponent`.

Both initial build and re-build after the change were successful.

**Comment by icecoldfire** [comment]
Could you retry step 2 with: ng build --aot --watch instead of ng serve?

**Comment by devoto13** [comment]
@icecoldfire Nope, still builds correctly.

<details>
  <summary>The versions of the packages I have</summary>

```
Angular CLI: 6.1.3
Node: 8.11.1
OS: darwin x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.7.3
@angular/cli                      6.1.3
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.3
@schematics/update                0.7.3
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
```

</details>

**Comment by Neofish22** [comment]
My reproduction actually fails to reproduce it. It did during creation but
then stopped.

You might be able to follow the steps I detailed in the readme.
Unfortunately I don't have the time to try further at the moment.

**Comment by mimopo** [comment]
Same problem here:

```
> ng serve --aot

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-08-13T12:00:48.705Z
Hash: 8cd9e0a058248a1a3739
Time: 8520ms
chunk {main} main.js, main.js.map (main) 25.4 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 184 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 2.82 MB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...

Date: 2018-08-13T12:00:59.263Z - Hash: b2c4a4b73fbcb0e90443 - Time: 1553ms
3 unchanged chunks
chunk {main} main.js, main.js.map (main) 25.2 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 2.8 MB [initial] [rendered]

ERROR in ./src/app/app.component.ngfactory.js
Module not found: Error: Can't resolve '@fortawesome/angular-fontawesome.ngfactory' in '/home/miguel/Projects/test/src/app'
ℹ ｢wdm｣: Failed to compile.
```

**Comment by devoto13** [comment]
The symptoms look very similar to https://github.com/angular/angular/issues/25424, so probably the root cause is in Angular itself, not angular-fontawesome.

**Comment by mimopo** [comment]
Thanks! 

Yes, It's seems to be an Angular problem. After downgrade all the angular components from 6.1.2 to 6.1.1 it works. I'll keep them fixed for the moment.

```
...
    "@angular/animations": "6.1.1",
    "@angular/common": "6.1.1",
    "@angular/compiler": "6.1.1",
    "@angular/core": "6.1.1",
    "@angular/forms": "6.1.1",
    "@angular/http": "6.1.1",
    "@angular/platform-browser": "6.1.1",
    "@angular/platform-browser-dynamic": "6.1.1",
    "@angular/router": "6.1.1",
...
```

**Comment by devoto13** [comment]
It says in https://github.com/angular/angular/issues/25424 that bug was fixed in Angular 6.1.6. Can anybody confirm that `angular-fontawesome` issue is resolved when using that version?

**Comment by icecoldfire** [comment]
@devoto13 Just updated to angular 6.1.7 and it seems fixed.

**Comment by devoto13** [comment]
Thanks for confirming, @icecoldfire. I'll keep this issue open for a couple more days and close if nobody reports same problem again.

**Comment by devoto13** [comment]
Closing as it seems to be fixed in the new version of Angular.

**Comment by albertzubkowicz** [comment]
issue persists on Angular 8.0.3, only running without --aot flag doesn't produce errors.
